[build-system]
requires = ["hatchling==1.27.0"]
build-backend = "hatchling.build"

[project]
name = "rox-dox"
version = "0.1.0"
description = "Offline documentation generator for Rox"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic==2.11.7",
    "tqdm==4.67.1",
]

[project.scripts]
rox-dox = "rox_dox.cli:main"

[dependency-groups]
dev = ["pytest==8.4.1", "ruff==0.12.2"]

[tool.hatch.build.targets.wheel]
packages = ["src/rox_dox"]
